name: myapp
description: A new Flutter project.


publish_to: "none" # Remove this if you plan to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  # UI
  google_fonts: ^8.0.0
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  table_calendar: ^3.1.2


  # File & PDF
  file_picker: ^10.3.9
  flutter_pdfview: ^1.3.2
  pdf: ^3.10.7
  printing: ^5.12.0
  dio: ^5.4.0
  open_filex: ^4.4.0
  http: ^1.2.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5


  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  cloud_functions: 6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/